# Generated by Django 4.2.7 on 2026-01-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_studied', models.IntegerField()),
                ('previous_scores', models.IntegerField()),
                ('extracurricular', models.BooleanField()),
                ('sleep_hours', models.IntegerField()),
                ('sample_papers', models.IntegerField()),
                ('performance_index', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Performance',
                'ordering': ['-created_at'],
            },
        ),
    ]
